pipeline {
    agent any
    parameters {
        choice (choices: ["NA-EST", "NA-CST", "EU-WST"], description: "Choose Env", name: "aZone")    
    }
    
    stages {
        stage('Initiate'){
            steps {echo "Choice is set to : ${params.aZone}"}
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Completed') {
            steps {
                echo 'Build Deployed'
            }
        }
    }
}
